#!/bin/bash

g++ -Wall -fPIC -I$ANTLR_HOME/antlr/libantlr3c-3.4/include -L/home/stbadmin/repository-manager/antlr/libantlr3c-3.4/lib -lantlr3c -c *.c;

g++ -shared -Wl,-soname,librepoparserlexer.so.1 -o librepoparserlexer.so.1.0 *.o;

cp librepoparserlexer.so.1.0 /home/stbadmin/repository-manager/antlr/libantlr3c-3.4/lib/;

ln -sf ./antlr/libantlr3c-3.4/lib/librepoparserlexer.so.1.0 ./antlr/libantlr3c-3.4/lib/librepoparserlexer.so.1;

ln -sf ./antlr/libantlr3c-3.4/lib/librepoparserlexer.so.1.0.//antlr/libantlr3c-3.4/lib/librepoparserlexer.so;

exit 0;
