/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /home/stbadmin/repository-manager/src/parser/RepositoryManager.g
 *     -                            On : 2016-01-20 16:04:36
 *     -                 for the lexer : RepositoryManagerLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */



/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "RepositoryManagerLexer.h"
/* ----------------------------------------- */


/** String literals used by RepositoryManagerLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x3A, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x64, 0x61, 0x74, 0x69, 0x6D, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x73, 0x61, 0x79, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x42, 0x45, 0x47, 0x49, 0x4E, 0x20, 0x4D, 0x50, 0x4B, 0x49, 0x20, 0x43, 0x52, 0x45, 0x44, 0x45, 0x4E, 0x54, 0x49, 0x41, 0x4C, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x45, 0x4E, 0x44, 0x20, 0x4D, 0x50, 0x4B, 0x49, 0x20, 0x43, 0x52, 0x45, 0x44, 0x45, 0x4E, 0x54, 0x49, 0x41, 0x4C, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x42, 0x45, 0x47, 0x49, 0x4E, 0x20, 0x50, 0x55, 0x42, 0x4C, 0x49, 0x43, 0x20, 0x4B, 0x45, 0x59, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x45, 0x4E, 0x44, 0x20, 0x50, 0x55, 0x42, 0x4C, 0x49, 0x43, 0x20, 0x4B, 0x45, 0x59, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x42, 0x45, 0x47, 0x49, 0x4E, 0x20, 0x53, 0x49, 0x47, 0x4E, 0x41, 0x54, 0x55, 0x52, 0x45, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x45, 0x4E, 0x44, 0x20, 0x53, 0x49, 0x47, 0x4E, 0x41, 0x54, 0x55, 0x52, 0x45, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x42, 0x45, 0x47, 0x49, 0x4E, 0x20, 0x56, 0x41, 0x4C, 0x49, 0x44, 0x49, 0x54, 0x59, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x45, 0x4E, 0x44, 0x20, 0x56, 0x41, 0x4C, 0x49, 0x44, 0x49, 0x54, 0x59, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_13[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x42, 0x45, 0x47, 0x49, 0x4E, 0x20, 0x4D, 0x50, 0x4B, 0x49, 0x20, 0x43, 0x45, 0x52, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x45, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_14[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x45, 0x4E, 0x44, 0x20, 0x4D, 0x50, 0x4B, 0x49, 0x20, 0x43, 0x45, 0x52, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x45, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_15[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x42, 0x45, 0x47, 0x49, 0x4E, 0x20, 0x4D, 0x50, 0x4B, 0x49, 0x20, 0x43, 0x48, 0x41, 0x4C, 0x4C, 0x45, 0x4E, 0x47, 0x45, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_16[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x45, 0x4E, 0x44, 0x20, 0x4D, 0x50, 0x4B, 0x49, 0x20, 0x43, 0x48, 0x41, 0x4C, 0x4C, 0x45, 0x4E, 0x47, 0x45, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_17[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x42, 0x45, 0x47, 0x49, 0x4E, 0x20, 0x4D, 0x50, 0x4B, 0x49, 0x20, 0x43, 0x48, 0x41, 0x4C, 0x4C, 0x45, 0x4E, 0x47, 0x45, 0x20, 0x52, 0x45, 0x53, 0x50, 0x4F, 0x4E, 0x53, 0x45, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_18[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x45, 0x4E, 0x44, 0x20, 0x4D, 0x50, 0x4B, 0x49, 0x20, 0x43, 0x48, 0x41, 0x4C, 0x4C, 0x45, 0x4E, 0x47, 0x45, 0x20, 0x52, 0x45, 0x53, 0x50, 0x4F, 0x4E, 0x53, 0x45, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_19[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x42, 0x45, 0x47, 0x49, 0x4E, 0x20, 0x52, 0x45, 0x50, 0x4F, 0x53, 0x49, 0x54, 0x4F, 0x52, 0x59, 0x20, 0x43, 0x4C, 0x49, 0x45, 0x4E, 0x54, 0x20, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_20[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x45, 0x4E, 0x44, 0x20, 0x52, 0x45, 0x50, 0x4F, 0x53, 0x49, 0x54, 0x4F, 0x52, 0x59, 0x20, 0x43, 0x4C, 0x49, 0x45, 0x4E, 0x54, 0x20, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_21[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x42, 0x45, 0x47, 0x49, 0x4E, 0x20, 0x52, 0x45, 0x50, 0x4F, 0x53, 0x49, 0x54, 0x4F, 0x52, 0x59, 0x20, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x20, 0x52, 0x45, 0x50, 0x4C, 0x59, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_22[]  = { 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x45, 0x4E, 0x44, 0x20, 0x52, 0x45, 0x50, 0x4F, 0x53, 0x49, 0x54, 0x4F, 0x52, 0x59, 0x20, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x20, 0x52, 0x45, 0x50, 0x4C, 0x59, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_23[]  = { 0x4E, 0x6F, 0x74, 0x20, 0x62, 0x65, 0x66, 0x6F, 0x72, 0x65, 0x3A,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_24[]  = { 0x4E, 0x6F, 0x74, 0x20, 0x61, 0x66, 0x74, 0x65, 0x72, 0x3A,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pRepositoryManagerLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pRepositoryManagerLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pRepositoryManagerLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pRepositoryManagerLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mT__39    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mT__40    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mT__41    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mT__42    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mT__43    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mT__44    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mT__45    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mT__46    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mNUM    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mTEXT    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mCREDENTIAL_HEADER    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mCREDENTIAL_END    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mPUBLIC_KEY_HEADER    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mPUBLIC_KEY_END    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mSIGNATURE_HEADER    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mSIGNATURE_END    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mVALIDITY_HEADER    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mVALIDITY_END    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mCERT_HEADER    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mCERT_END    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mCHALLENGE_HEADER    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mCHALLENGE_END    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mRESPONSE_HEADER    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mRESPONSE_END    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mREQUEST_HEADER    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mREQUEST_END    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mREPLY_HEADER    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mREPLY_END    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mNOT_BEFORE    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mNOT_AFTER    (pRepositoryManagerLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pRepositoryManagerLexer ctx);
static void	RepositoryManagerLexerFree(pRepositoryManagerLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
RepositoryManagerLexerFree  (pRepositoryManagerLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
RepositoryManagerLexerReset (pRepositoryManagerLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/home/stbadmin/repository-manager/src/parser/RepositoryManager.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called RepositoryManagerLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pRepositoryManagerLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pRepositoryManagerLexer RepositoryManagerLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return RepositoryManagerLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called RepositoryManagerLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pRepositoryManagerLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pRepositoryManagerLexer RepositoryManagerLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pRepositoryManagerLexer ctx; // Context structure we will build and return

    ctx = (pRepositoryManagerLexer) ANTLR3_CALLOC(1, sizeof(RepositoryManagerLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in RepositoryManagerLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our RepositoryManagerLexer interface
     */
    ctx->mT__39	= mT__39;
    ctx->mT__40	= mT__40;
    ctx->mT__41	= mT__41;
    ctx->mT__42	= mT__42;
    ctx->mT__43	= mT__43;
    ctx->mT__44	= mT__44;
    ctx->mT__45	= mT__45;
    ctx->mT__46	= mT__46;
    ctx->mWS	= mWS;
    ctx->mNUM	= mNUM;
    ctx->mTEXT	= mTEXT;
    ctx->mCREDENTIAL_HEADER	= mCREDENTIAL_HEADER;
    ctx->mCREDENTIAL_END	= mCREDENTIAL_END;
    ctx->mPUBLIC_KEY_HEADER	= mPUBLIC_KEY_HEADER;
    ctx->mPUBLIC_KEY_END	= mPUBLIC_KEY_END;
    ctx->mSIGNATURE_HEADER	= mSIGNATURE_HEADER;
    ctx->mSIGNATURE_END	= mSIGNATURE_END;
    ctx->mVALIDITY_HEADER	= mVALIDITY_HEADER;
    ctx->mVALIDITY_END	= mVALIDITY_END;
    ctx->mCERT_HEADER	= mCERT_HEADER;
    ctx->mCERT_END	= mCERT_END;
    ctx->mCHALLENGE_HEADER	= mCHALLENGE_HEADER;
    ctx->mCHALLENGE_END	= mCHALLENGE_END;
    ctx->mRESPONSE_HEADER	= mRESPONSE_HEADER;
    ctx->mRESPONSE_END	= mRESPONSE_END;
    ctx->mREQUEST_HEADER	= mREQUEST_HEADER;
    ctx->mREQUEST_END	= mREQUEST_END;
    ctx->mREPLY_HEADER	= mREPLY_HEADER;
    ctx->mREPLY_END	= mREPLY_END;
    ctx->mNOT_BEFORE	= mNOT_BEFORE;
    ctx->mNOT_AFTER	= mNOT_AFTER;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= RepositoryManagerLexerFree;
    ctx->reset          = RepositoryManagerLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | WS | NUM | TEXT | CREDENTIAL_HEADER | CREDENTIAL_END | PUBLIC_KEY_HEADER | PUBLIC_KEY_END | SIGNATURE_HEADER | SIGNATURE_END | VALIDITY_HEADER | VALIDITY_END | CERT_HEADER | CERT_END | CHALLENGE_HEADER | CHALLENGE_END | RESPONSE_HEADER | RESPONSE_END | REQUEST_HEADER | REQUEST_END | REPLY_HEADER | REPLY_END | NOT_BEFORE | NOT_AFTER );
 */
static const ANTLR3_INT32 dfa4_eot[121] =
    {
	11, -1, -1, -1, -1, 14, 14, 14, 14, -1, 11, -1, 14, 14, -1, 21, 14, 14, 
	14, 14, 14, -1, 14, 14, 14, 14, 14, 14, 14, 34, 14, -1, 14, 14, -1, 14, 
	-1, -1, 42, 14, 14, 14, -1, 46, 14, 14, -1, 14, 14, 14, -1, 14, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa4_eof[121] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa4_min[121] =
    {
	9, -1, -1, -1, -1, 45, 97, 101, 97, -1, 43, -1, 45, 111, -1, 43, 116, 113, 
	121, 45, 116, -1, 105, 117, 115, 45, 32, 109, 101, 43, 45, 97, 101, 115, 
	-1, 66, -1, -1, 43, 116, 69, 78, -1, 43, 71, 68, -1, 73, 32, 78, 77, 32, 
	80, -1, -1, -1, 69, 77, 75, 80, 80, -1, -1, -1, 69, 73, 79, 75, 80, 32, 
	83, 73, 79, 67, 73, 32, 83, 69, 84, 67, 73, -1, -1, 65, 79, 69, 84, 76, 
	82, -1, -1, 65, 79, 76, 89, 76, 82, 69, 32, 76, 89, 78, 67, 69, 32, 71, 
	-1, -1, 78, 67, 69, 71, -1, -1, 32, 69, -1, -1, 32, -1, -1
    };
static const ANTLR3_INT32 dfa4_max[121] =
    {
	122, -1, -1, -1, -1, 45, 97, 101, 97, -1, 122, -1, 45, 111, -1, 122, 116, 
	113, 121, 45, 116, -1, 105, 117, 115, 45, 32, 109, 101, 122, 45, 98, 101, 
	115, -1, 69, -1, -1, 122, 116, 69, 78, -1, 122, 71, 68, -1, 73, 32, 78, 
	86, 32, 80, -1, -1, -1, 69, 86, 75, 80, 80, -1, -1, -1, 69, 73, 79, 75, 
	80, 32, 83, 73, 79, 67, 73, 32, 83, 82, 84, 67, 73, -1, -1, 65, 79, 82, 
	84, 76, 82, -1, -1, 65, 79, 76, 89, 76, 82, 69, 32, 76, 89, 78, 83, 69, 
	32, 71, -1, -1, 78, 83, 69, 71, -1, -1, 45, 69, -1, -1, 45, -1, -1
    };
static const ANTLR3_INT32 dfa4_accept[121] =
    {
	-1, 1, 2, 3, 4, -1, -1, -1, -1, 9, -1, 10, -1, -1, 11, -1, -1, -1, -1, 
	-1, -1, 5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 8, -1, 30, 31, 
	-1, -1, -1, -1, 6, -1, -1, -1, 7, -1, -1, -1, -1, -1, -1, 15, 17, 19, -1, 
	-1, -1, -1, -1, 14, 16, 18, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, 13, 21, -1, -1, -1, -1, -1, -1, 12, 20, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 27, 29, -1, -1, -1, 
	-1, 26, 28, -1, -1, 23, 25, -1, 22, 24
    };
static const ANTLR3_INT32 dfa4_special[121] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa4_T_empty	    NULL

static const ANTLR3_INT32 dfa4_T0[] =
    {
	26
    };

static const ANTLR3_INT32 dfa4_T1[] =
    {
	59
    };

static const ANTLR3_INT32 dfa4_T2[] =
    {
	20
    };

static const ANTLR3_INT32 dfa4_T3[] =
    {
	31
    };

static const ANTLR3_INT32 dfa4_T4[] =
    {
	14, -1, 14, -1, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, -1, -1, 
	14, -1, -1, -1, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 
	14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, -1, -1, -1, -1, 14, -1, 
	14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 
	14, 14, 14, 14, 14, 14, 14, 14
    };

static const ANTLR3_INT32 dfa4_T5[] =
    {
	30
    };

static const ANTLR3_INT32 dfa4_T6[] =
    {
	19
    };

static const ANTLR3_INT32 dfa4_T7[] =
    {
	102
    };

static const ANTLR3_INT32 dfa4_T8[] =
    {
	106, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 107
    };

static const ANTLR3_INT32 dfa4_T9[] =
    {
	25
    };

static const ANTLR3_INT32 dfa4_T10[] =
    {
	94
    };

static const ANTLR3_INT32 dfa4_T11[] =
    {
	98
    };

static const ANTLR3_INT32 dfa4_T12[] =
    {
	84
    };

static const ANTLR3_INT32 dfa4_T13[] =
    {
	88
    };

static const ANTLR3_INT32 dfa4_T14[] =
    {
	74
    };

static const ANTLR3_INT32 dfa4_T15[] =
    {
	78
    };

static const ANTLR3_INT32 dfa4_T16[] =
    {
	66
    };

static const ANTLR3_INT32 dfa4_T17[] =
    {
	70
    };

static const ANTLR3_INT32 dfa4_T18[] =
    {
	100
    };

static const ANTLR3_INT32 dfa4_T19[] =
    {
	96
    };

static const ANTLR3_INT32 dfa4_T20[] =
    {
	109
    };

static const ANTLR3_INT32 dfa4_T21[] =
    {
	104
    };

static const ANTLR3_INT32 dfa4_T22[] =
    {
	47
    };

static const ANTLR3_INT32 dfa4_T23[] =
    {
	80
    };

static const ANTLR3_INT32 dfa4_T24[] =
    {
	76
    };

static const ANTLR3_INT32 dfa4_T25[] =
    {
	92
    };

static const ANTLR3_INT32 dfa4_T26[] =
    {
	44
    };

static const ANTLR3_INT32 dfa4_T27[] =
    {
	86
    };

static const ANTLR3_INT32 dfa4_T28[] =
    {
	72
    };

static const ANTLR3_INT32 dfa4_T29[] =
    {
	68
    };

static const ANTLR3_INT32 dfa4_T30[] =
    {
	90, -1, -1, 91, -1, -1, -1, -1, -1, -1, -1, -1, -1, 89
    };

static const ANTLR3_INT32 dfa4_T31[] =
    {
	101
    };

static const ANTLR3_INT32 dfa4_T32[] =
    {
	97
    };

static const ANTLR3_INT32 dfa4_T33[] =
    {
	85
    };

static const ANTLR3_INT32 dfa4_T34[] =
    {
	110
    };

static const ANTLR3_INT32 dfa4_T35[] =
    {
	105
    };

static const ANTLR3_INT32 dfa4_T36[] =
    {
	37, 36
    };

static const ANTLR3_INT32 dfa4_T37[] =
    {
	57
    };

static const ANTLR3_INT32 dfa4_T38[] =
    {
	79
    };

static const ANTLR3_INT32 dfa4_T39[] =
    {
	35
    };

static const ANTLR3_INT32 dfa4_T40[] =
    {
	75
    };

static const ANTLR3_INT32 dfa4_T41[] =
    {
	93
    };

static const ANTLR3_INT32 dfa4_T42[] =
    {
	87
    };

static const ANTLR3_INT32 dfa4_T43[] =
    {
	51
    };

static const ANTLR3_INT32 dfa4_T44[] =
    {
	117, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 116
    };

static const ANTLR3_INT32 dfa4_T45[] =
    {
	112, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 113
    };

static const ANTLR3_INT32 dfa4_T46[] =
    {
	114
    };

static const ANTLR3_INT32 dfa4_T47[] =
    {
	40, -1, -1, 41
    };

static const ANTLR3_INT32 dfa4_T48[] =
    {
	49
    };

static const ANTLR3_INT32 dfa4_T49[] =
    {
	14, -1, 14, -1, 14, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 14, -1, -1, 
	14, -1, -1, -1, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 
	14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, -1, -1, -1, -1, 14, -1, 
	14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 
	14, 14, 14, 14, 14, 14, 14, 14
    };

static const ANTLR3_INT32 dfa4_T50[] =
    {
	52, -1, -1, 53, -1, 56, 54, -1, -1, 55
    };

static const ANTLR3_INT32 dfa4_T51[] =
    {
	71
    };

static const ANTLR3_INT32 dfa4_T52[] =
    {
	67
    };

static const ANTLR3_INT32 dfa4_T53[] =
    {
	60, -1, -1, 61, -1, 64, 62, -1, -1, 63
    };

static const ANTLR3_INT32 dfa4_T54[] =
    {
	15
    };

static const ANTLR3_INT32 dfa4_T55[] =
    {
	38
    };

static const ANTLR3_INT32 dfa4_T56[] =
    {
	27
    };

static const ANTLR3_INT32 dfa4_T57[] =
    {
	32
    };

static const ANTLR3_INT32 dfa4_T58[] =
    {
	16
    };

static const ANTLR3_INT32 dfa4_T59[] =
    {
	22
    };

static const ANTLR3_INT32 dfa4_T60[] =
    {
	39
    };

static const ANTLR3_INT32 dfa4_T61[] =
    {
	115
    };

static const ANTLR3_INT32 dfa4_T62[] =
    {
	33
    };

static const ANTLR3_INT32 dfa4_T63[] =
    {
	28
    };

static const ANTLR3_INT32 dfa4_T64[] =
    {
	118
    };

static const ANTLR3_INT32 dfa4_T65[] =
    {
	23
    };

static const ANTLR3_INT32 dfa4_T66[] =
    {
	17
    };

static const ANTLR3_INT32 dfa4_T67[] =
    {
	120, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 119
    };

static const ANTLR3_INT32 dfa4_T68[] =
    {
	29
    };

static const ANTLR3_INT32 dfa4_T69[] =
    {
	24
    };

static const ANTLR3_INT32 dfa4_T70[] =
    {
	99
    };

static const ANTLR3_INT32 dfa4_T71[] =
    {
	18
    };

static const ANTLR3_INT32 dfa4_T72[] =
    {
	103
    };

static const ANTLR3_INT32 dfa4_T73[] =
    {
	108
    };

static const ANTLR3_INT32 dfa4_T74[] =
    {
	111
    };

static const ANTLR3_INT32 dfa4_T75[] =
    {
	43
    };

static const ANTLR3_INT32 dfa4_T76[] =
    {
	9, 9, -1, -1, 9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, 9, -1, -1, -1, -1, -1, -1, -1, 1, 2, -1, 14, 3, 12, 4, 
	14, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 5, -1, -1, 14, -1, -1, -1, 
	14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 13, 14, 14, 14, 14, 
	14, 14, 14, 14, 14, 14, 14, 14, -1, -1, -1, -1, 14, -1, 14, 14, 14, 6, 
	14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 7, 8, 14, 14, 14, 14, 
	14, 14, 14
    };

static const ANTLR3_INT32 dfa4_T77[] =
    {
	65
    };

static const ANTLR3_INT32 dfa4_T78[] =
    {
	95
    };

static const ANTLR3_INT32 dfa4_T79[] =
    {
	58
    };

static const ANTLR3_INT32 dfa4_T80[] =
    {
	48
    };

static const ANTLR3_INT32 dfa4_T81[] =
    {
	50
    };

static const ANTLR3_INT32 dfa4_T82[] =
    {
	73
    };

static const ANTLR3_INT32 dfa4_T83[] =
    {
	69
    };

static const ANTLR3_INT32 dfa4_T84[] =
    {
	82, -1, -1, 83, -1, -1, -1, -1, -1, -1, -1, -1, -1, 81
    };

static const ANTLR3_INT32 dfa4_T85[] =
    {
	77
    };

static const ANTLR3_INT32 dfa4_T86[] =
    {
	45
    };


/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa4_transitions[] =
{
    dfa4_T76, NULL, NULL, NULL, NULL, dfa4_T54, dfa4_T58, dfa4_T66, dfa4_T71, 
    NULL, dfa4_T49, NULL, dfa4_T6, dfa4_T2, NULL, dfa4_T4, dfa4_T59, dfa4_T65, 
    dfa4_T69, dfa4_T9, dfa4_T0, NULL, dfa4_T56, dfa4_T63, dfa4_T68, dfa4_T5, 
    dfa4_T3, dfa4_T57, dfa4_T62, dfa4_T4, dfa4_T39, dfa4_T36, dfa4_T55, 
    dfa4_T60, NULL, dfa4_T47, NULL, NULL, dfa4_T4, dfa4_T75, dfa4_T26, dfa4_T86, 
    NULL, dfa4_T4, dfa4_T22, dfa4_T80, NULL, dfa4_T48, dfa4_T81, dfa4_T43, 
    dfa4_T50, dfa4_T37, dfa4_T79, NULL, NULL, NULL, dfa4_T1, dfa4_T53, dfa4_T77, 
    dfa4_T16, dfa4_T52, NULL, NULL, NULL, dfa4_T29, dfa4_T83, dfa4_T17, 
    dfa4_T51, dfa4_T28, dfa4_T82, dfa4_T14, dfa4_T40, dfa4_T24, dfa4_T85, 
    dfa4_T15, dfa4_T38, dfa4_T23, dfa4_T84, dfa4_T12, dfa4_T33, dfa4_T27, 
    NULL, NULL, dfa4_T42, dfa4_T13, dfa4_T30, dfa4_T25, dfa4_T41, dfa4_T10, 
    NULL, NULL, dfa4_T78, dfa4_T19, dfa4_T32, dfa4_T11, dfa4_T70, dfa4_T18, 
    dfa4_T31, dfa4_T7, dfa4_T72, dfa4_T21, dfa4_T35, dfa4_T8, dfa4_T73, 
    dfa4_T20, dfa4_T34, NULL, NULL, dfa4_T74, dfa4_T45, dfa4_T46, dfa4_T61, 
    NULL, NULL, dfa4_T44, dfa4_T64, NULL, NULL, dfa4_T67, NULL, NULL
};


/* Declare tracking structure for Cyclic DFA 4
 */
static
ANTLR3_CYCLIC_DFA cdfa4
    =	{
	    4,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1:1: Tokens : ( T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | WS | NUM | TEXT | CREDENTIAL_HEADER | CREDENTIAL_END | PUBLIC_KEY_HEADER | PUBLIC_KEY_END | SIGNATURE_HEADER | SIGNATURE_END | VALIDITY_HEADER | VALIDITY_END | CERT_HEADER | CERT_END | CHALLENGE_HEADER | CHALLENGE_END | RESPONSE_HEADER | RESPONSE_END | REQUEST_HEADER | REQUEST_END | REPLY_HEADER | REPLY_END | NOT_BEFORE | NOT_AFTER );",
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/

	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa4_eot,	    /* EOT table			    */
	    dfa4_eof,	    /* EOF table			    */
	    dfa4_min,	    /* Minimum tokens for each state    */
	    dfa4_max,	    /* Maximum tokens for each state    */
	    dfa4_accept,	/* Accept table			    */
	    dfa4_special,	/* Special transition states	    */
	    dfa4_transitions	/* Table of transition tables	    */

	};
/* End of Cyclic DFA 4
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 11:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__39
 *
 * Looks to match the characters the constitute the token T__39
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__39(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__39;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:11:7: ( '(' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:11:9: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto ruleT__39Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__39Ex; /* Prevent compiler warnings */
    ruleT__39Ex: ;

}
// $ANTLR end T__39

//   Comes from: 12:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__40
 *
 * Looks to match the characters the constitute the token T__40
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__40(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__40;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:12:7: ( ')' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:12:9: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto ruleT__40Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__40Ex; /* Prevent compiler warnings */
    ruleT__40Ex: ;

}
// $ANTLR end T__40

//   Comes from: 13:7: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__41
 *
 * Looks to match the characters the constitute the token T__41
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__41(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__41;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:13:7: ( ',' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:13:9: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleT__41Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__41Ex; /* Prevent compiler warnings */
    ruleT__41Ex: ;

}
// $ANTLR end T__41

//   Comes from: 14:7: ( '.' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__42
 *
 * Looks to match the characters the constitute the token T__42
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__42(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__42;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:14:7: ( '.' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:14:9: '.'
    {
        MATCHC('.');
        if  (HASEXCEPTION())
        {
            goto ruleT__42Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__42Ex; /* Prevent compiler warnings */
    ruleT__42Ex: ;

}
// $ANTLR end T__42

//   Comes from: 15:7: ( ':-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__43
 *
 * Looks to match the characters the constitute the token T__43
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__43(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__43;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:15:7: ( ':-' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:15:9: ':-'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleT__43Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__43Ex; /* Prevent compiler warnings */
    ruleT__43Ex: ;

}
// $ANTLR end T__43

//   Comes from: 16:7: ( 'datime' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__44
 *
 * Looks to match the characters the constitute the token T__44
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__44(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__44;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:16:7: ( 'datime' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:16:9: 'datime'
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleT__44Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__44Ex; /* Prevent compiler warnings */
    ruleT__44Ex: ;

}
// $ANTLR end T__44

//   Comes from: 17:7: ( 'request' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__45
 *
 * Looks to match the characters the constitute the token T__45
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__45(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__45;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:17:7: ( 'request' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:17:9: 'request'
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleT__45Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__45Ex; /* Prevent compiler warnings */
    ruleT__45Ex: ;

}
// $ANTLR end T__45

//   Comes from: 18:7: ( 'says' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__46
 *
 * Looks to match the characters the constitute the token T__46
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__46(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__46;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:18:7: ( 'says' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:18:9: 'says'
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleT__46Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__46Ex; /* Prevent compiler warnings */
    ruleT__46Ex: ;

}
// $ANTLR end T__46

//   Comes from: 91:9: ( ( ' ' | '\\t' | '\\n' | '\\r' '\\u000C' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:91:9: ( ( ' ' | '\\t' | '\\n' | '\\r' '\\u000C' )+ )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:91:12: ( ' ' | '\\t' | '\\n' | '\\r' '\\u000C' )+
    {
        // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:91:12: ( ' ' | '\\t' | '\\n' | '\\r' '\\u000C' )+
        {
            int cnt1=0;

            for (;;)
            {
                int alt1=5;
        	switch ( LA(1) )
        	{
        	case ' ':
        		{
        			alt1=1;
        		}
        	    break;
        	case '\t':
        		{
        			alt1=2;
        		}
        	    break;
        	case '\n':
        		{
        			alt1=3;
        		}
        	    break;
        	case '\r':
        		{
        			alt1=4;
        		}
        	    break;

        	}

        	switch (alt1)
        	{
        	    case 1:
        	        // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:91:13: ' '
        	        {
        	            MATCHC(' ');
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;
        	    case 2:
        	        // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:91:17: '\\t'
        	        {
        	            MATCHC('\t');
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;
        	    case 3:
        	        // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:91:22: '\\n'
        	        {
        	            MATCHC('\n');
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;
        	    case 4:
        	        // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:91:27: '\\r' '\\u000C'
        	        {
        	            MATCHC('\r');
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleWSEx;
        	            }


        	            MATCHC(0x000C);
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt1 >= 1 )
        		{
        		    goto loop1;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt1++;
            }
            loop1: ;	/* Jump to here if this rule does not match */
        }

        {
            LEXSTATE->channel=99;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

//   Comes from: 94:6: ( ( '0' .. '9' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NUM
 *
 * Looks to match the characters the constitute the token NUM
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNUM(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NUM;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:94:6: ( ( '0' .. '9' )* )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:94:10: ( '0' .. '9' )*
    {
        // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:94:10: ( '0' .. '9' )*

        for (;;)
        {
            int alt2=2;
            switch ( LA(1) )
            {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            	{
            		alt2=1;
            	}
                break;

            }

            switch (alt2)
            {
        	case 1:
        	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:
        	    {
        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleNUMEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop2;	/* break out of the loop */
        	    break;
            }
        }
        loop2: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNUMEx; /* Prevent compiler warnings */
    ruleNUMEx: ;

}
// $ANTLR end NUM

//   Comes from: 97:7: ( ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '/' | '+' | '=' | '_' | '-' | ':' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start TEXT
 *
 * Looks to match the characters the constitute the token TEXT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mTEXT(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = TEXT;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:97:7: ( ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '/' | '+' | '=' | '_' | '-' | ':' )* )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:97:10: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '/' | '+' | '=' | '_' | '-' | ':' )*
    {
        // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:97:10: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '/' | '+' | '=' | '_' | '-' | ':' )*

        for (;;)
        {
            int alt3=2;
            switch ( LA(1) )
            {
            case '+':
            case '-':
            case '/':
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case ':':
            case '=':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt3=1;
            	}
                break;

            }

            switch (alt3)
            {
        	case 1:
        	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:
        	    {
        	        if ( LA(1) == '+' || LA(1) == '-' || ((LA(1) >= '/') && (LA(1) <= ':')) || LA(1) == '=' || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleTEXTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop3;	/* break out of the loop */
        	    break;
            }
        }
        loop3: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleTEXTEx; /* Prevent compiler warnings */
    ruleTEXTEx: ;

}
// $ANTLR end TEXT

//   Comes from: 100:18: ( '-----BEGIN MPKI CREDENTIAL-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CREDENTIAL_HEADER
 *
 * Looks to match the characters the constitute the token CREDENTIAL_HEADER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCREDENTIAL_HEADER(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CREDENTIAL_HEADER;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:100:18: ( '-----BEGIN MPKI CREDENTIAL-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:100:19: '-----BEGIN MPKI CREDENTIAL-----'
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleCREDENTIAL_HEADEREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCREDENTIAL_HEADEREx; /* Prevent compiler warnings */
    ruleCREDENTIAL_HEADEREx: ;

}
// $ANTLR end CREDENTIAL_HEADER

//   Comes from: 101:15: ( '-----END MPKI CREDENTIAL-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CREDENTIAL_END
 *
 * Looks to match the characters the constitute the token CREDENTIAL_END
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCREDENTIAL_END(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CREDENTIAL_END;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:101:15: ( '-----END MPKI CREDENTIAL-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:101:16: '-----END MPKI CREDENTIAL-----'
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleCREDENTIAL_ENDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCREDENTIAL_ENDEx; /* Prevent compiler warnings */
    ruleCREDENTIAL_ENDEx: ;

}
// $ANTLR end CREDENTIAL_END

//   Comes from: 102:18: ( '-----BEGIN PUBLIC KEY-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PUBLIC_KEY_HEADER
 *
 * Looks to match the characters the constitute the token PUBLIC_KEY_HEADER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPUBLIC_KEY_HEADER(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PUBLIC_KEY_HEADER;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:102:18: ( '-----BEGIN PUBLIC KEY-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:102:19: '-----BEGIN PUBLIC KEY-----'
    {
        MATCHS(lit_7);
        if  (HASEXCEPTION())
        {
            goto rulePUBLIC_KEY_HEADEREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePUBLIC_KEY_HEADEREx; /* Prevent compiler warnings */
    rulePUBLIC_KEY_HEADEREx: ;

}
// $ANTLR end PUBLIC_KEY_HEADER

//   Comes from: 103:15: ( '-----END PUBLIC KEY-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PUBLIC_KEY_END
 *
 * Looks to match the characters the constitute the token PUBLIC_KEY_END
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPUBLIC_KEY_END(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PUBLIC_KEY_END;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:103:15: ( '-----END PUBLIC KEY-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:103:16: '-----END PUBLIC KEY-----'
    {
        MATCHS(lit_8);
        if  (HASEXCEPTION())
        {
            goto rulePUBLIC_KEY_ENDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePUBLIC_KEY_ENDEx; /* Prevent compiler warnings */
    rulePUBLIC_KEY_ENDEx: ;

}
// $ANTLR end PUBLIC_KEY_END

//   Comes from: 104:17: ( '-----BEGIN SIGNATURE-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SIGNATURE_HEADER
 *
 * Looks to match the characters the constitute the token SIGNATURE_HEADER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSIGNATURE_HEADER(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = SIGNATURE_HEADER;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:104:17: ( '-----BEGIN SIGNATURE-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:104:18: '-----BEGIN SIGNATURE-----'
    {
        MATCHS(lit_9);
        if  (HASEXCEPTION())
        {
            goto ruleSIGNATURE_HEADEREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSIGNATURE_HEADEREx; /* Prevent compiler warnings */
    ruleSIGNATURE_HEADEREx: ;

}
// $ANTLR end SIGNATURE_HEADER

//   Comes from: 105:14: ( '-----END SIGNATURE-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SIGNATURE_END
 *
 * Looks to match the characters the constitute the token SIGNATURE_END
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSIGNATURE_END(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = SIGNATURE_END;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:105:14: ( '-----END SIGNATURE-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:105:15: '-----END SIGNATURE-----'
    {
        MATCHS(lit_10);
        if  (HASEXCEPTION())
        {
            goto ruleSIGNATURE_ENDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSIGNATURE_ENDEx; /* Prevent compiler warnings */
    ruleSIGNATURE_ENDEx: ;

}
// $ANTLR end SIGNATURE_END

//   Comes from: 106:16: ( '-----BEGIN VALIDITY-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start VALIDITY_HEADER
 *
 * Looks to match the characters the constitute the token VALIDITY_HEADER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mVALIDITY_HEADER(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = VALIDITY_HEADER;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:106:16: ( '-----BEGIN VALIDITY-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:106:17: '-----BEGIN VALIDITY-----'
    {
        MATCHS(lit_11);
        if  (HASEXCEPTION())
        {
            goto ruleVALIDITY_HEADEREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleVALIDITY_HEADEREx; /* Prevent compiler warnings */
    ruleVALIDITY_HEADEREx: ;

}
// $ANTLR end VALIDITY_HEADER

//   Comes from: 107:13: ( '-----END VALIDITY-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start VALIDITY_END
 *
 * Looks to match the characters the constitute the token VALIDITY_END
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mVALIDITY_END(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = VALIDITY_END;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:107:13: ( '-----END VALIDITY-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:107:14: '-----END VALIDITY-----'
    {
        MATCHS(lit_12);
        if  (HASEXCEPTION())
        {
            goto ruleVALIDITY_ENDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleVALIDITY_ENDEx; /* Prevent compiler warnings */
    ruleVALIDITY_ENDEx: ;

}
// $ANTLR end VALIDITY_END

//   Comes from: 108:12: ( '-----BEGIN MPKI CERTIFICATE-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CERT_HEADER
 *
 * Looks to match the characters the constitute the token CERT_HEADER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCERT_HEADER(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CERT_HEADER;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:108:12: ( '-----BEGIN MPKI CERTIFICATE-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:108:13: '-----BEGIN MPKI CERTIFICATE-----'
    {
        MATCHS(lit_13);
        if  (HASEXCEPTION())
        {
            goto ruleCERT_HEADEREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCERT_HEADEREx; /* Prevent compiler warnings */
    ruleCERT_HEADEREx: ;

}
// $ANTLR end CERT_HEADER

//   Comes from: 109:9: ( '-----END MPKI CERTIFICATE-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CERT_END
 *
 * Looks to match the characters the constitute the token CERT_END
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCERT_END(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CERT_END;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:109:9: ( '-----END MPKI CERTIFICATE-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:109:10: '-----END MPKI CERTIFICATE-----'
    {
        MATCHS(lit_14);
        if  (HASEXCEPTION())
        {
            goto ruleCERT_ENDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCERT_ENDEx; /* Prevent compiler warnings */
    ruleCERT_ENDEx: ;

}
// $ANTLR end CERT_END

//   Comes from: 110:17: ( '-----BEGIN MPKI CHALLENGE-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CHALLENGE_HEADER
 *
 * Looks to match the characters the constitute the token CHALLENGE_HEADER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCHALLENGE_HEADER(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CHALLENGE_HEADER;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:110:17: ( '-----BEGIN MPKI CHALLENGE-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:110:18: '-----BEGIN MPKI CHALLENGE-----'
    {
        MATCHS(lit_15);
        if  (HASEXCEPTION())
        {
            goto ruleCHALLENGE_HEADEREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCHALLENGE_HEADEREx; /* Prevent compiler warnings */
    ruleCHALLENGE_HEADEREx: ;

}
// $ANTLR end CHALLENGE_HEADER

//   Comes from: 111:14: ( '-----END MPKI CHALLENGE-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CHALLENGE_END
 *
 * Looks to match the characters the constitute the token CHALLENGE_END
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCHALLENGE_END(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CHALLENGE_END;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:111:14: ( '-----END MPKI CHALLENGE-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:111:15: '-----END MPKI CHALLENGE-----'
    {
        MATCHS(lit_16);
        if  (HASEXCEPTION())
        {
            goto ruleCHALLENGE_ENDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCHALLENGE_ENDEx; /* Prevent compiler warnings */
    ruleCHALLENGE_ENDEx: ;

}
// $ANTLR end CHALLENGE_END

//   Comes from: 112:16: ( '-----BEGIN MPKI CHALLENGE RESPONSE-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RESPONSE_HEADER
 *
 * Looks to match the characters the constitute the token RESPONSE_HEADER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRESPONSE_HEADER(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RESPONSE_HEADER;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:112:16: ( '-----BEGIN MPKI CHALLENGE RESPONSE-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:112:17: '-----BEGIN MPKI CHALLENGE RESPONSE-----'
    {
        MATCHS(lit_17);
        if  (HASEXCEPTION())
        {
            goto ruleRESPONSE_HEADEREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleRESPONSE_HEADEREx; /* Prevent compiler warnings */
    ruleRESPONSE_HEADEREx: ;

}
// $ANTLR end RESPONSE_HEADER

//   Comes from: 113:13: ( '-----END MPKI CHALLENGE RESPONSE-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RESPONSE_END
 *
 * Looks to match the characters the constitute the token RESPONSE_END
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRESPONSE_END(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RESPONSE_END;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:113:13: ( '-----END MPKI CHALLENGE RESPONSE-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:113:14: '-----END MPKI CHALLENGE RESPONSE-----'
    {
        MATCHS(lit_18);
        if  (HASEXCEPTION())
        {
            goto ruleRESPONSE_ENDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleRESPONSE_ENDEx; /* Prevent compiler warnings */
    ruleRESPONSE_ENDEx: ;

}
// $ANTLR end RESPONSE_END

//   Comes from: 114:15: ( '-----BEGIN REPOSITORY CLIENT REQUEST-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start REQUEST_HEADER
 *
 * Looks to match the characters the constitute the token REQUEST_HEADER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mREQUEST_HEADER(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = REQUEST_HEADER;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:114:15: ( '-----BEGIN REPOSITORY CLIENT REQUEST-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:114:16: '-----BEGIN REPOSITORY CLIENT REQUEST-----'
    {
        MATCHS(lit_19);
        if  (HASEXCEPTION())
        {
            goto ruleREQUEST_HEADEREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleREQUEST_HEADEREx; /* Prevent compiler warnings */
    ruleREQUEST_HEADEREx: ;

}
// $ANTLR end REQUEST_HEADER

//   Comes from: 115:12: ( '-----END REPOSITORY CLIENT REQUEST-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start REQUEST_END
 *
 * Looks to match the characters the constitute the token REQUEST_END
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mREQUEST_END(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = REQUEST_END;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:115:12: ( '-----END REPOSITORY CLIENT REQUEST-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:115:13: '-----END REPOSITORY CLIENT REQUEST-----'
    {
        MATCHS(lit_20);
        if  (HASEXCEPTION())
        {
            goto ruleREQUEST_ENDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleREQUEST_ENDEx; /* Prevent compiler warnings */
    ruleREQUEST_ENDEx: ;

}
// $ANTLR end REQUEST_END

//   Comes from: 116:13: ( '-----BEGIN REPOSITORY SERVER REPLY-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start REPLY_HEADER
 *
 * Looks to match the characters the constitute the token REPLY_HEADER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mREPLY_HEADER(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = REPLY_HEADER;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:116:13: ( '-----BEGIN REPOSITORY SERVER REPLY-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:116:14: '-----BEGIN REPOSITORY SERVER REPLY-----'
    {
        MATCHS(lit_21);
        if  (HASEXCEPTION())
        {
            goto ruleREPLY_HEADEREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleREPLY_HEADEREx; /* Prevent compiler warnings */
    ruleREPLY_HEADEREx: ;

}
// $ANTLR end REPLY_HEADER

//   Comes from: 117:10: ( '-----END REPOSITORY SERVER REPLY-----' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start REPLY_END
 *
 * Looks to match the characters the constitute the token REPLY_END
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mREPLY_END(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = REPLY_END;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:117:10: ( '-----END REPOSITORY SERVER REPLY-----' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:117:11: '-----END REPOSITORY SERVER REPLY-----'
    {
        MATCHS(lit_22);
        if  (HASEXCEPTION())
        {
            goto ruleREPLY_ENDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleREPLY_ENDEx; /* Prevent compiler warnings */
    ruleREPLY_ENDEx: ;

}
// $ANTLR end REPLY_END

//   Comes from: 119:4: ( 'Not before:' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NOT_BEFORE
 *
 * Looks to match the characters the constitute the token NOT_BEFORE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNOT_BEFORE(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NOT_BEFORE;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:119:4: ( 'Not before:' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:119:4: 'Not before:'
    {
        MATCHS(lit_23);
        if  (HASEXCEPTION())
        {
            goto ruleNOT_BEFOREEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNOT_BEFOREEx; /* Prevent compiler warnings */
    ruleNOT_BEFOREEx: ;

}
// $ANTLR end NOT_BEFORE

//   Comes from: 121:4: ( 'Not after:' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NOT_AFTER
 *
 * Looks to match the characters the constitute the token NOT_AFTER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNOT_AFTER(pRepositoryManagerLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NOT_AFTER;


    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:121:4: ( 'Not after:' )
    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:121:4: 'Not after:'
    {
        MATCHS(lit_24);
        if  (HASEXCEPTION())
        {
            goto ruleNOT_AFTEREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNOT_AFTEREx; /* Prevent compiler warnings */
    ruleNOT_AFTEREx: ;

}
// $ANTLR end NOT_AFTER

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pRepositoryManagerLexer ctx)
{
    {
        //  /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:8: ( T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | WS | NUM | TEXT | CREDENTIAL_HEADER | CREDENTIAL_END | PUBLIC_KEY_HEADER | PUBLIC_KEY_END | SIGNATURE_HEADER | SIGNATURE_END | VALIDITY_HEADER | VALIDITY_END | CERT_HEADER | CERT_END | CHALLENGE_HEADER | CHALLENGE_END | RESPONSE_HEADER | RESPONSE_END | REQUEST_HEADER | REQUEST_END | REPLY_HEADER | REPLY_END | NOT_BEFORE | NOT_AFTER )

        ANTLR3_UINT32 alt4;

        alt4=31;

        alt4 = cdfa4.predict(ctx, RECOGNIZER, ISTREAM, &cdfa4);
        if  (HASEXCEPTION())
        {
            goto ruleTokensEx;
        }

        switch (alt4)
        {
    	case 1:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:10: T__39
    	    {
    	        /* 1:10: T__39 */
    	        mT__39(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:16: T__40
    	    {
    	        /* 1:16: T__40 */
    	        mT__40(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:22: T__41
    	    {
    	        /* 1:22: T__41 */
    	        mT__41(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:28: T__42
    	    {
    	        /* 1:28: T__42 */
    	        mT__42(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:34: T__43
    	    {
    	        /* 1:34: T__43 */
    	        mT__43(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:40: T__44
    	    {
    	        /* 1:40: T__44 */
    	        mT__44(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:46: T__45
    	    {
    	        /* 1:46: T__45 */
    	        mT__45(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:52: T__46
    	    {
    	        /* 1:52: T__46 */
    	        mT__46(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:58: WS
    	    {
    	        /* 1:58: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:61: NUM
    	    {
    	        /* 1:61: NUM */
    	        mNUM(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:65: TEXT
    	    {
    	        /* 1:65: TEXT */
    	        mTEXT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:70: CREDENTIAL_HEADER
    	    {
    	        /* 1:70: CREDENTIAL_HEADER */
    	        mCREDENTIAL_HEADER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:88: CREDENTIAL_END
    	    {
    	        /* 1:88: CREDENTIAL_END */
    	        mCREDENTIAL_END(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:103: PUBLIC_KEY_HEADER
    	    {
    	        /* 1:103: PUBLIC_KEY_HEADER */
    	        mPUBLIC_KEY_HEADER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:121: PUBLIC_KEY_END
    	    {
    	        /* 1:121: PUBLIC_KEY_END */
    	        mPUBLIC_KEY_END(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:136: SIGNATURE_HEADER
    	    {
    	        /* 1:136: SIGNATURE_HEADER */
    	        mSIGNATURE_HEADER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:153: SIGNATURE_END
    	    {
    	        /* 1:153: SIGNATURE_END */
    	        mSIGNATURE_END(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:167: VALIDITY_HEADER
    	    {
    	        /* 1:167: VALIDITY_HEADER */
    	        mVALIDITY_HEADER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:183: VALIDITY_END
    	    {
    	        /* 1:183: VALIDITY_END */
    	        mVALIDITY_END(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:196: CERT_HEADER
    	    {
    	        /* 1:196: CERT_HEADER */
    	        mCERT_HEADER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:208: CERT_END
    	    {
    	        /* 1:208: CERT_END */
    	        mCERT_END(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:217: CHALLENGE_HEADER
    	    {
    	        /* 1:217: CHALLENGE_HEADER */
    	        mCHALLENGE_HEADER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:234: CHALLENGE_END
    	    {
    	        /* 1:234: CHALLENGE_END */
    	        mCHALLENGE_END(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:248: RESPONSE_HEADER
    	    {
    	        /* 1:248: RESPONSE_HEADER */
    	        mRESPONSE_HEADER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 25:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:264: RESPONSE_END
    	    {
    	        /* 1:264: RESPONSE_END */
    	        mRESPONSE_END(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 26:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:277: REQUEST_HEADER
    	    {
    	        /* 1:277: REQUEST_HEADER */
    	        mREQUEST_HEADER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 27:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:292: REQUEST_END
    	    {
    	        /* 1:292: REQUEST_END */
    	        mREQUEST_END(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 28:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:304: REPLY_HEADER
    	    {
    	        /* 1:304: REPLY_HEADER */
    	        mREPLY_HEADER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 29:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:317: REPLY_END
    	    {
    	        /* 1:317: REPLY_END */
    	        mREPLY_END(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 30:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:327: NOT_BEFORE
    	    {
    	        /* 1:327: NOT_BEFORE */
    	        mNOT_BEFORE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 31:
    	    // /home/stbadmin/repository-manager/src/parser/RepositoryManager.g:1:338: NOT_AFTER
    	    {
    	        /* 1:338: NOT_AFTER */
    	        mNOT_AFTER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
